spring.application.name=usperdi

# ==============
# BANCO DE DADOS
# ==============

# Por enquanto as credenciais estao hardcoded, depois tem que colocar num .env file

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/usperdi}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# nao deixa o banco perder conexao

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1


# ===========
# HEALTHCHECK
# ===========

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.db.enabled=true