spring.application.name=usperdi

# ==============
# BANCO DE DADOS
# ==============

# Por enquanto as credenciais estão hardcoded, depois tem que colocar num .env file

spring.datasource.url=jdbc:postgresql://localhost:5432/usperdi
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Não deixa o banco perder conexão

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1


# ===========
# HEALTHCHECK
# ===========

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.db.enabled=true